### ISSUE TITLE
Publishing to Heroku does not run gulp

### ISSUE THREAD

**Issue by stay2be** [linnovate/mean#1675]
The documentation for publishing to Heroku is quite incomplete. Deploying to Heroku does not bundle the app with gulp so I get a blank screen with 'MEAN.io makes building apps simpler and faster' and the bundled js file is not found '/bundle/app.js'.

This is when using GitLab CI Runner and publishing with dpl. Additionally, there is no build script in the package.json file, so I'm not sure how to create the assets for production instead of just running 'gulp' in development.

'node server' is only working, when the app is pre-bundled with gulp.

**Comment by timelf123** [comment]
This is what I did in `package.json`. add ` "cross-env": "^3.0.0",` to deps (to set env variables across win/mac/nix)

```
    "build:production": "cross-env NODE_ENV=production webpack",
    "postinstall": "node tools/scripts/postinstall.js && npm run build:production",

```

**Comment by gaesteliste030** [comment]
@timelf123 thanks for your suggestion. After hours of trying to get this working I'm finally done.

The problem with your approach is that in order to run webpack devDependencies are required. Wenn deploying this to Heroku the NODE_ENV is set to 'production' (because we don't want to have devDependencies on the final server) and webpack fails.

These are the steps to get the whole chain (GitLab -> GitLab CI Runner -> Heroku) working:

#1: npm install --save cross-env

#2: add another script to package.json 'build:production' but leave 'postinstall' as it is:
```
"scripts": {
    "start:dev": "gulp",
    "start": "node server",
    "mocha": "node tools/test/run-mocha.js",
    "karma": "node node_modules/karma/bin/karma start karma.conf.js",
    "test": "gulp test",
    "test-e2e": "gulp e2e.test",
    "build:production": "cross-env NODE_ENV=production webpack",
    "postinstall": "node tools/scripts/postinstall.js",
    "snyk-protect": "snyk protect",
    "prepublish": "npm run snyk-protect"
  }
```

#3: add '.gitlab-ci.yml':
```
image: mwallasch/docker-ruby-node # required, because we need ruby, node and npm

variables:
  NODE_ENV: "development" # required, because we need to install devDependencies

stages:
  - deploy

deploy_job:
  stage: deploy
  script:
  - npm -v
  - npm install -qs # install all dependencies (and devDependencies)
  - npm run build:production # run webpack, set NODE_ENV=production
  - gem install dpl # install dpl...
  - dpl --skip_cleanup --provider=heroku --app=<app-name> --api-key=$HEROKU_API_KEY #...and deploy (skip_cleanup prevents deleting the previous generated bundled assets)
  only:
  - master
```

#4: add another line to '.slugignore' because we don't want to deploy the devDependencies to Heroku:
```
/node_modules
```
This requires Heroku to re-install all dependencies (but not the devDependencies). 

Now we got the assets bundled and deployed to Heroku.
I'm not sure if this is the right approach to do, especially for bundling css assets. But this is the next thing to figure out.

If this is a right approach, maybe this could be included in the docs for people using this chain:
```
> GitLab -> GitLab CI Runner (via .gitlab-ci.yml) -> Heroku
```
